services:
  - type: web
    name: php-app
    env: docker
    plan: free
    dockerContext: ./project
    dockerfilePath: ./project/Dockerfile
    autoDeploy: true
    envVars:
      - key: PORT
        value: "80"